// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartShip.AdminService.Infrastructure.Data;

#nullable disable

namespace SmartShip.AdminService.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20260429152810_AddHubCoordinatesAndSeedData")]
    partial class AddHubCoordinatesAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartShip.AdminService.Domain.Entities.DashboardMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveShipments")
                        .HasColumnType("int");

                    b.Property<int>("DeliveredToday")
                        .HasColumnType("int");

                    b.Property<int>("Exceptions")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalCustomers")
                        .HasColumnType("int");

                    b.Property<int>("TotalShipments")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DashboardMetrics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveShipments = 0,
                            DeliveredToday = 0,
                            Exceptions = 0,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalCustomers = 0,
                            TotalShipments = 0
                        });
                });

            modelBuilder.Entity("SmartShip.AdminService.Domain.Entities.Hub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Delhi",
                            ContactPhone = "9800000001",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 28.613900000000001,
                            Longitude = 77.209000000000003,
                            Name = "Delhi Hub",
                            State = "Delhi"
                        },
                        new
                        {
                            Id = 2,
                            City = "Mumbai",
                            ContactPhone = "9800000002",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 19.076000000000001,
                            Longitude = 72.877700000000004,
                            Name = "Mumbai Hub",
                            State = "Maharashtra"
                        },
                        new
                        {
                            Id = 101,
                            City = "Bengaluru",
                            ContactPhone = "9800000003",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 12.9716,
                            Longitude = 77.5946,
                            Name = "Bangalore Hub",
                            State = "Karnataka"
                        },
                        new
                        {
                            Id = 102,
                            City = "Hyderabad",
                            ContactPhone = "9800000004",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 17.385000000000002,
                            Longitude = 78.486699999999999,
                            Name = "Hyderabad Hub",
                            State = "Telangana"
                        },
                        new
                        {
                            Id = 103,
                            City = "Chennai",
                            ContactPhone = "9800000005",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 13.082700000000001,
                            Longitude = 80.270700000000005,
                            Name = "Chennai Hub",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 104,
                            City = "Kolkata",
                            ContactPhone = "9800000006",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 22.572600000000001,
                            Longitude = 88.363900000000001,
                            Name = "Kolkata Hub",
                            State = "West Bengal"
                        },
                        new
                        {
                            Id = 105,
                            City = "Jalandhar",
                            ContactPhone = "9800000007",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 31.326000000000001,
                            Longitude = 75.5762,
                            Name = "Jalandhar Hub",
                            State = "Punjab"
                        },
                        new
                        {
                            Id = 106,
                            City = "Lucknow",
                            ContactPhone = "9800000008",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 26.846699999999998,
                            Longitude = 80.946200000000005,
                            Name = "Lucknow Hub",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 107,
                            City = "Pune",
                            ContactPhone = "9800000009",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 18.520399999999999,
                            Longitude = 73.856700000000004,
                            Name = "Pune Hub",
                            State = "Maharashtra"
                        },
                        new
                        {
                            Id = 108,
                            City = "Ahmedabad",
                            ContactPhone = "9800000010",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 23.022500000000001,
                            Longitude = 72.571399999999997,
                            Name = "Ahmedabad Hub",
                            State = "Gujarat"
                        },
                        new
                        {
                            Id = 109,
                            City = "Jaipur",
                            ContactPhone = "9800000011",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 26.912400000000002,
                            Longitude = 75.787300000000002,
                            Name = "Jaipur Hub",
                            State = "Rajasthan"
                        },
                        new
                        {
                            Id = 110,
                            City = "Chandigarh",
                            ContactPhone = "9800000012",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 30.7333,
                            Longitude = 76.779399999999995,
                            Name = "Chandigarh Hub",
                            State = "Chandigarh"
                        },
                        new
                        {
                            Id = 111,
                            City = "Indore",
                            ContactPhone = "9800000013",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 22.7196,
                            Longitude = 75.857699999999994,
                            Name = "Indore Hub",
                            State = "Madhya Pradesh"
                        },
                        new
                        {
                            Id = 112,
                            City = "Nagpur",
                            ContactPhone = "9800000014",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 21.145800000000001,
                            Longitude = 79.088200000000001,
                            Name = "Nagpur Hub",
                            State = "Maharashtra"
                        },
                        new
                        {
                            Id = 113,
                            City = "Patna",
                            ContactPhone = "9800000015",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 25.609300000000001,
                            Longitude = 85.137600000000006,
                            Name = "Patna Hub",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 114,
                            City = "Bhopal",
                            ContactPhone = "9800000016",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 23.259899999999998,
                            Longitude = 77.412599999999998,
                            Name = "Bhopal Hub",
                            State = "Madhya Pradesh"
                        },
                        new
                        {
                            Id = 115,
                            City = "Kochi",
                            ContactPhone = "9800000017",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 9.9312000000000005,
                            Longitude = 76.267300000000006,
                            Name = "Kochi Hub",
                            State = "Kerala"
                        },
                        new
                        {
                            Id = 116,
                            City = "Guwahati",
                            ContactPhone = "9800000018",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 26.144500000000001,
                            Longitude = 91.736199999999997,
                            Name = "Guwahati Hub",
                            State = "Assam"
                        },
                        new
                        {
                            Id = 117,
                            City = "Coimbatore",
                            ContactPhone = "9800000019",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 11.0168,
                            Longitude = 76.955799999999996,
                            Name = "Coimbatore Hub",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 118,
                            City = "Visakhapatnam",
                            ContactPhone = "9800000020",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 17.686800000000002,
                            Longitude = 83.218500000000006,
                            Name = "Visakhapatnam Hub",
                            State = "Andhra Pradesh"
                        });
                });

            modelBuilder.Entity("SmartShip.AdminService.Domain.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
